output "api_url" {
  description = "OpenShift cluster API endpoint."
  value       = openshift_cluster.this.api_url
}

output "console_url" {
  description = "OpenShift web console URL."
  value       = openshift_cluster.this.console_url
}

output "kubeconfig_path" {
  description = "Path to the generated kubeconfig file."
  value       = openshift_cluster.this.kubeconfig_path
}

output "kubeadmin_password_path" {
  description = "Path to the kubeadmin-password file."
  value       = openshift_cluster.this.kubeadmin_password_path
}

output "cluster_id" {
  description = "Cluster infrastructure ID."
  value       = openshift_cluster.this.cluster_id
}

output "registry_url" {
  description = "Internal mirror registry URL."
  value       = openshift_mirror_registry.internal.registry_url
}

output "registry_ca_cert" {
  description = "CA certificate for the internal mirror registry (self-signed)."
  value       = openshift_mirror_registry.internal.ca_cert
  sensitive   = true
}

output "image_content_sources" {
  description = "imageContentSources entries generated by oc mirror."
  value       = openshift_image_mirror.release.image_content_sources
}

output "install_config_rendered" {
  description = "The rendered install-config.yaml content."
  value       = openshift_install_config.cluster.rendered
  sensitive   = true
}

output "local_storage_subscription_state" {
  description = "Current state of the Local Storage Operator subscription."
  value       = openshift_subscription.local_storage.state
}

output "local_storage_installed_csv" {
  description = "Currently installed CSV for the Local Storage Operator."
  value       = openshift_subscription.local_storage.installed_csv
}
